//
//  UserReviewsInteractor.swift
//  MovieApp
//
//  Created by k1d_dev on 14/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class UserReviewsInteractor {
    
    // MARK: - Public properties -
    let movieId: String
    
    // MARK: - Private properties
    private let service: NetworkService
    
    init(movieId: String, service: NetworkService = NetworkService.shared) {
        self.movieId = movieId
        self.service = service
    }
    
}

// MARK: - Extensions -

extension UserReviewsInteractor: UserReviewsInteractorInterface {
    
    func getMovieReviews(id: String, page: String) async throws -> TMDBApiResult<UserReview>? {
        if let url = MovieDetailEndpoint.userReview(id).urlEndpoint {
            return try await self.service.performRequest(url: url, payload: ["page": page])
        }
        return nil
    }
    
}
