//
//  UserReviewsInterfaces.swift
//  MovieApp
//
//  Created by k1d_dev on 14/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol UserReviewsWireframeInterface: WireframeInterface {
}

protocol UserReviewsViewInterface: ViewInterface {
    func applySnapshot(items: [UserReviewItem])
}

protocol UserReviewsPresenterInterface: PresenterInterface {
    var page: Int { get set }
    
    func getUserReviews() async throws
}

protocol UserReviewsInteractorInterface: InteractorInterface {
    var movieId: String { get }
    
    func getMovieReviews(id: String, page: String) async throws -> TMDBApiResult<UserReview>?
}
