//
//  UserReviewsPresenter.swift
//  MovieApp
//
//  Created by k1d_dev on 14/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class UserReviewsPresenter {

    var page: Int = 1
    // MARK: - Private properties -

    private weak var view: UserReviewsViewInterface?
    private let interactor: UserReviewsInteractorInterface
    private let wireframe: UserReviewsWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: UserReviewsViewInterface?,
        interactor: UserReviewsInteractorInterface,
        wireframe: UserReviewsWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension UserReviewsPresenter: UserReviewsPresenterInterface {
    
    func getUserReviews() async throws {
        
        let reviewResults = try? await interactor.getMovieReviews(id: "\(interactor.movieId)", page: "\(page)")
        
        if let reviews = reviewResults?.results as? [UserReview], !reviews.isEmpty {
            let reviewItems = reviews.map { UserReviewItem(section: .userReview, type: .userReviews($0)) }
            view?.applySnapshot(items: reviewItems)
        }
        
    }
}
