//
//  MovieListInteractor.swift
//  MovieApp
//
//  Created by k1d_dev on 11/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
    
    // MARK: - Public properties -
    var movieId: String?
    
    // MARK: - Private properties -
    private let service: NetworkService
    
    init(movieId: String?, service: NetworkService = NetworkService.shared) {
        self.movieId = movieId
        self.service = service
    }
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
    
    func discoverMovie(by id: String) async throws -> MovieResults? {
        if let url = MovieListEndpoint.movieList.urlEndpoint {
            return try await self.service.performRequest(url: url, payload: ["with_genres": id])
        }
        return nil
    }
    
}
