//
//  MovieListInteractor.swift
//  MovieApp
//
//  Created by Engkit on 11/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
}
