//
//  MovieListInterfaces.swift
//  MovieApp
//
//  Created by k1d_dev on 11/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
    func navigateToMovieDetails(destination: MovieListNavigationOption, _ navigationController: UINavigationController?)
}

protocol MovieListViewInterface: ViewInterface {
    func applySnapshot(item: [MovieListItem])
}

protocol MovieListPresenterInterface: PresenterInterface {
    func discoverMovie() async throws
    func navigate(to destination: MovieListNavigationOption, navigationController: UINavigationController?)
}

protocol MovieListInteractorInterface: InteractorInterface {
    var movieId: String { get }
    func discoverMovie(by id: String) async throws -> TMDBApiResult<Movie>?
}
