workflows:
  main:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      xcode: latest
    scripts:
    - name: Archive iOS app
      script: |
        xcodebuild -workspace MovieApp.xcworkspace -scheme MovieApp -configuration Release -archivePath build/MovieApp.xcarchive archive
        xcodebuild -exportArchive -archivePath build/MovieApp.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
    artifacts:
    - build/**/*.ipa
    publishing:
        email:
          recipients:
            - engkidsr@gmail.com
