//
//  HomePresenter.swift
//  MovieApp
//
//  Created by Engkit on 11/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {

    // MARK: - Private properties -

    private weak var view: HomeViewInterface?
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: HomeViewInterface?,
        interactor: HomeInteractorInterface,
        wireframe: HomeWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    
    func getGenreList() async throws {
        
        Task {
            do {
                
                let genresModel = try await interactor.getGenreList()
                
                let homeItem = genresModel.genres.map { HomeItem(section: .genreList, type: .genreList(.init(movieId: $0.movieId, name: $0.name)))}
                
                view?.applySnapshot(item: homeItem)
            } catch let error {
                debugPrint(error)
            }
        }
        
    }
}
