//
//  HomeInterfaces.swift
//  MovieApp
//
//  Created by k1d_dev on 11/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to destination: HomeNavigationOption, navigationController: UINavigationController?)
}

protocol HomeViewInterface: ViewInterface {
    func applySnapshot(item: [HomeItem])
}

protocol HomePresenterInterface: PresenterInterface {
    func getGenreList() async throws
    func navigate(to destination: HomeNavigationOption, navigationController: UINavigationController?)
}

protocol HomeInteractorInterface: InteractorInterface {
    func getGenreList() async throws -> Genres?
}
