//
//  HomeViewController.swift
//  MovieApp
//
//  Created by Engkit on 11/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: HomePresenterInterface!
    
    // MARK: - Private properties -
    
    private lazy var collectionView: UICollectionView = {
        let collectionView = UICollectionView(
            frame: .zero,
            collectionViewLayout: self.createLayout()
        )
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        //        collectionView.delegate = self
        collectionView.backgroundColor = .white
        return collectionView
    }()

    private var dataSource: UICollectionViewDiffableDataSource<HomeSection, HomeItem>!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Movie App"
        self.view.addSubview(collectionView)
        self.setupViews()
        self.configureDataSource()
        self.applySnapshot()
    }
    
    private func setupViews(insets: UIEdgeInsets = .zero) {
        
        collectionView.registerCellWithoutNib(GenreListCell.self)
        
        NSLayoutConstraint.activate([
            self.collectionView.topAnchor.constraint(equalTo: self.view.topAnchor, constant: insets.top),
            self.collectionView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: insets.right),
            self.collectionView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: insets.left),
            self.collectionView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: insets.bottom)
        ])
        
    }
    
    private func createLayout() -> UICollectionViewCompositionalLayout {
        
        let config = UICollectionViewCompositionalLayoutConfiguration()
        config.interSectionSpacing = 16
        
        return UICollectionViewCompositionalLayout(sectionProvider: { sectionIndex, _ in
            let sections = HomeSection(rawValue: sectionIndex)
            
            switch sections {
            case .genreList:
                
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .estimated(50)
                    )
                )
                let group = NSCollectionLayoutGroup.horizontal(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .estimated(50)
                    ),
                    subitems: [item]
                )
                let section = NSCollectionLayoutSection(group: group)
                section.contentInsets = .init(
                    top: 16,
                    leading: 16,
                    bottom: 20,
                    trailing: 16
                )
                return section
            case .none:
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .fractionalHeight(1)
                    )
                )
                let group = NSCollectionLayoutGroup.horizontal(
                    layoutSize: .init(
                        widthDimension: .absolute(0),
                        heightDimension: .absolute(0)
                    ),
                    subitems: [item]
                )
                
                let section = NSCollectionLayoutSection(group: group)
                
                return section
            }
        }, configuration: config)
    }
    
    private func configureDataSource() {
        dataSource = UICollectionViewDiffableDataSource<HomeSection, HomeItem>(collectionView: collectionView) { (collectionView, indexPath, itemIdentifier) -> UICollectionViewCell? in
            
            switch itemIdentifier.type {
            case .genreList(let model):
                let cell = collectionView.dequeueReusableCell(withClass: GenreListCell.self, for: indexPath) as GenreListCell
                
                cell.configure(model: model)
                
                return cell
            }
            
        }
    }
    
    func applySnapshot() {
        var snapshot = NSDiffableDataSourceSnapshot<HomeSection, HomeItem>()
        
        snapshot.appendSections([.genreList])
        let item: [HomeItem] = [
            .init(section: .genreList, type: .genreList(.init(movieId: 0, name: "Sci-fi"))),
            .init(section: .genreList, type: .genreList(.init(movieId: 1, name: "Horror"))),
            .init(section: .genreList, type: .genreList(.init(movieId: 2, name: "Adventure"))),
            .init(section: .genreList, type: .genreList(.init(movieId: 3, name: "Drama"))),
            .init(section: .genreList, type: .genreList(.init(movieId: 4, name: "Comedy"))),
            .init(section: .genreList, type: .genreList(.init(movieId: 5, name: "Action")))
            
        ]
        snapshot.appendItems(item)
        
        dataSource.apply(snapshot, animatingDifferences: true)
    }

}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}
