//
//  MovieDetailViewController.swift
//  MovieApp
//
//  Created by k1d_dev on 12/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: MovieDetailPresenterInterface!
    
    // MARK: - Private properties -
    private lazy var collectionView: UICollectionView = {
        let collectionView = UICollectionView(
            frame: .zero,
            collectionViewLayout: self.createLayout()
        )
        collectionView.translatesAutoresizingMaskIntoConstraints = false
//        collectionView.delegate = self
        collectionView.backgroundColor = .white
        return collectionView
    }()
    
    private var dataSource: UICollectionViewDiffableDataSource<MovieDetailSection, MovieDetailItem>!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.addSubview(collectionView)
        self.title = presenter.title
        self.setupViews()
        self.configureDataSource()
        
        Task {
            try await self.presenter.viewDidLoad()
        }
        
    }
    
    // MARK: - Private functions -
    
    private func setupViews(insets: UIEdgeInsets = .zero) {
        
        collectionView.registerCellWithoutNib(MovieDetailCell.self)
        collectionView.registerCellWithoutNib(UserReviewCell.self)
        
        NSLayoutConstraint.activate([
            self.collectionView.topAnchor.constraint(equalTo: self.view.topAnchor, constant: insets.top),
            self.collectionView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: insets.right),
            self.collectionView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: insets.left),
            self.collectionView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: insets.bottom)
        ])
        
    }
    
    private func createLayout() -> UICollectionViewCompositionalLayout {
        
        let config = UICollectionViewCompositionalLayoutConfiguration()
        config.interSectionSpacing = 16
        
        return UICollectionViewCompositionalLayout(sectionProvider: { sectionIndex, _ in
            let sections = MovieDetailSection(rawValue: sectionIndex)
            
            switch sections {
            case .moviedetail:
                
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .fractionalHeight(0.75)
                    )
                )
                let group = NSCollectionLayoutGroup.vertical(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .fractionalHeight(1)
                    ),
                    subitems: [item]
                )
                let section = NSCollectionLayoutSection(group: group)
                section.contentInsets = .init(
                    top: 16,
                    leading: 16,
                    bottom: 20,
                    trailing: 16
                )
                return section
            case .movieTrailer:
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .estimated(1)
                    )
                )
                let group = NSCollectionLayoutGroup.horizontal(
                    layoutSize: .init(
                        widthDimension: .absolute(1),
                        heightDimension: .estimated(1)
                    ),
                    subitems: [item]
                )
                
                let section = NSCollectionLayoutSection(group: group)
                section.contentInsets = .init(
                    top: 16,
                    leading: 16,
                    bottom: 20,
                    trailing: 16
                )
                
                return section
            case .userReview:
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .estimated(130)
                    )
                )
                let group = NSCollectionLayoutGroup.horizontal(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .estimated(130)
                    ),
                    subitems: [item]
                )
                
                let section = NSCollectionLayoutSection(group: group)
                section.contentInsets = .init(
                    top: 16,
                    leading: 16,
                    bottom: 20,
                    trailing: 16
                )
                
                return section
            case .none:
                let item = NSCollectionLayoutItem(
                    layoutSize: .init(
                        widthDimension: .fractionalWidth(1),
                        heightDimension: .fractionalHeight(1)
                    )
                )
                let group = NSCollectionLayoutGroup.horizontal(
                    layoutSize: .init(
                        widthDimension: .estimated(1),
                        heightDimension: .estimated(1)
                    ),
                    subitems: [item]
                )
                
                let section = NSCollectionLayoutSection(group: group)
                
                return section
            }
        }, configuration: config)
    }

    private func configureDataSource() {
        dataSource = UICollectionViewDiffableDataSource<MovieDetailSection, MovieDetailItem>(collectionView: collectionView) { (collectionView, indexPath, itemIdentifier) -> UICollectionViewCell? in
            switch itemIdentifier.type {
            case .movieDetail(let movie):
                let cell = collectionView.dequeueReusableCell(withClass: MovieDetailCell.self, for: indexPath)
                
                cell.configure(model: movie)
                
                return cell
            case .movieTrailer:
                let cell = collectionView.dequeueReusableCell(withClass: MovieDetailCell.self, for: indexPath)
                
//                cell.configure(model: movie)
                
                return cell
            case .userReviews(let userReview):
                let cell = collectionView.dequeueReusableCell(withClass: UserReviewCell.self, for: indexPath)
                
                cell.configure(review: userReview)
                
                return cell
            }
        }
    }
    
}

// MARK: - Extensions -

extension MovieDetailViewController: MovieDetailViewInterface {
    
    func applySnapshot(items: [MovieDetailItem]) {
        var snapshot = NSDiffableDataSourceSnapshot<MovieDetailSection, MovieDetailItem>()
        
        snapshot.appendSections([.moviedetail, .movieTrailer, .userReview])
        
        for item in items {
            
            switch item.type {
            case .movieDetail(let movie):
                snapshot.appendItems([.init(section: .moviedetail, type: .movieDetail(movie))], toSection: .moviedetail)
            case .userReviews(let review):
                snapshot.appendItems([.init(section: .userReview, type: .userReviews(review))], toSection: .userReview)
            case .movieTrailer:
                
                return
            }
        }
        
        dataSource.apply(snapshot, animatingDifferences: true)
    }
}
