//
//  MovieDetailInterfaces.swift
//  MovieApp
//
//  Created by k1d_dev on 12/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieDetailWireframeInterface: WireframeInterface {
}

protocol MovieDetailViewInterface: ViewInterface {
    func applySnapshot(items: [MovieDetailItem])
}

protocol MovieDetailPresenterInterface: PresenterInterface {
    var title: String { get set }
    
    func viewDidLoad() async throws
}

protocol MovieDetailInteractorInterface: InteractorInterface {
    var movie: Movie { get }
    
    func getMovieReviews(id: String) async throws -> TMDBApiResult<UserReview>?
}
