//
//  MovieDetailInteractor.swift
//  MovieApp
//
//  Created by k1d_dev on 12/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailInteractor {
    
    // MARK: - Public properties
    let movie: Movie
    
    init(movie: Movie) {
        self.movie = movie
    }
    
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
    
}
