//
//  MovieDetailInteractor.swift
//  MovieApp
//
//  Created by k1d_dev on 12/08/23.
//  Copyright (c) 2023 k1d_dev. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailInteractor {
    
    // MARK: - Public properties
    let movie: Movie
    
    // MARK: - Private properties
    private let service: NetworkService
    
    init(movie: Movie, service: NetworkService = NetworkService.shared) {
        self.movie = movie
        self.service = service
    }
    
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
    func getMovieReviews(id: String) async throws -> TMDBApiResult<UserReview>? {
        if let url = MovieDetailEndpoint.userReview(id).urlEndpoint {
            return try await self.service.performRequest(url: url)
        }
        return nil
    }
}
